input_feature_dimensions: 126  # (draft encoding + embeddings)

# operational configs
use_gpu: True
model_save_directory: "models"
name: "win-rate-model"
run_number: 0

# training/validation configs
transform_prediction_for_reward: False
epochs: 15
early_stopping_rounds: 15
training_batch_size: 2_000
validation_batch_size: 10_000
learning_rate: 0.001
weight_decay_coef: 0.01